info:
  app:
    name: '@project.name@'
    description: '@project.description@'
  build:
    groupId: '@project.groupId@'
    artifact: '@project.artifactId@'
    version: '@project.version@'
  env:
    java:
      vendor: ${java.specification.vendor}
      vm-name: ${java.vm.name}
      runtime-version: ${java.runtime.version}

spring:
  datasource-blue:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://10.70.30.26:1433;databaseName=Blue_TST
    username: blue_api_tst
    password: fygut9cwQ9kknh5UT4BK
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: BlueHikariPool
      connection-timeout: 60000

  datasource-controle:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://10.70.30.26:1433;databaseName=ControleAcesso_Blue_TST
    username: blue_api_tst
    password: fygut9cwQ9kknh5UT4BK
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: ControleHikariPool
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      format_sql: true

app:
  historico:
      host: http://api-hist-dev.com

#  profiles:
#    active: dev

#k8s:
#  pathSwagger: ${PATH_SWAGGER}

